 name: Create Release Branch

on:
  push:
    branches:
      - main

inputs:
  release_version_no:
    description: ‘Version no of release
    required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Create release branch
      uses: actions/run-command@v1
      with:
        command: git checkout -b release/release-${{ inputs. release_version_no }} main

    - name: Push release branch
      uses: actions/upload-artifact@v2
      with:
        name: Release Branch
        path: release/release-${{ inputs. release_version_no }}

