name: Create Release Branch

on:
  workflow_dispatch:

inputs:
  release_version:
    description: 'version no of release'
    required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Create Release Branch
        run: |
          git checkout -b release/release-`${{ inputs.release_version }}`
          
      - name: Update Version and Name
        run: |
          sed -i "s/versionName .*/versionName `${{ inputs.release_version }}`/" app/build.gradle
        shell: bash

      - name: Create Release Branch
        run: |
	  git add -A
	  git commit -m "Updatinf version name"
	  git push origin release/release-`${{ inputs.release_version }}`

