name: Create Release Branch

on:
  workflow_dispatch:

inputs:
  release_version:
    description: 'version no of release'
    required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Create Release Branch
        run: |
          git checkout -b release/release-`{{inputs.release_version}}`
          git push origin release/release-`{{inputs.release_version}}`
