name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'version no of release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Create Release Branch
        run: |
          git checkout -b release/release-${{inputs.release_version}}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          sed -ie 's/versionName .*/versionName ${{inputs.release_version}}/' app/build.gradle         
          git commit -m "Automated commit by GitHub Actions to update version name" -a
          git push --set-upstream origin release/release-${{inputs.release_version}}

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.TOKEN_FOR_PR}}
          script: |
            const title = 'Release Pull Request';
            const branch = 'release/release-${{inputs.release_version}}';
            const { data } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              head: branch,
              base: 'main'
            });
            console.log(`Created Pull Request: ${data.html_url}`);
